export const endpoints = {
  auth: {
    login: '/auth/login',
    register: '/auth/register',
    verifyEmail: '/auth/verify-email',
    resendEmailVerification: '/auth/email-verification/resend',
    me: '/auth/me',
    forgotPassword: '/auth/forgot-password',
    resetPassword: '/auth/reset-password',
  },
  products: '/products',
  productImages: '/product-images/upload',
  variantTypes: '/variant-types',
  categories: '/categories',
  brands: '/brands',
  banners: '/banners',
  logo: '/logo',
  cart: '/cart',
  cartItems: '/cart/items',
  cartCheckout: '/cart/checkout',
  confirmBakongPayment: (orderId) => `/orders/${orderId}/bakong/confirm`,
  adminBanners: '/admin/banners',
  adminBannerImages: '/admin/banners/upload',
  adminLogos: '/admin/logos',
  adminLogoImage: '/admin/logos/upload',
  orders: '/orders',
  me: '/me',
  meAvatar: '/me/avatar',
  users: '/users',
}
