name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy on VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: root
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/myapp/project_e-commerce
            git fetch origin main
            git reset --hard origin/main
            git clean -fd
            docker compose run --rm backend composer install
            docker compose up -d --build
            docker compose exec backend php artisan migrate --force
            docker compose restart backend
